version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - infra-net
    command: redis-server --appendonly yes

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: redis://redis:6379
    networks:
      - infra-net

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Hach1997!
      MYSQL_DATABASE: tododb
      MYSQL_USER: td_su
      MYSQL_PASSWORD: Hach1997!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - infra-net

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: td_su:Hach1997!@(mysql:3306)/
    depends_on:
      - mysql
    networks:
      - infra-net

volumes:
  redis-data:
  mysql-data:

networks:
  infra-net:
    external: true
    name: infra-net
